### ISSUE TITLE
TypeError: catppuccin is not a function

### ISSUE THREAD

**Issue by gin-18** [catppuccin/daisyui#49]
I followed the readme to configure tailwind.config.js, but I got an error "TypeError: catppuccin is not a function"

my tailwind.config.js is set up like this:
```js
import daisyui from 'daisyui'
import catppuccin from '@catppuccin/daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [daisyui],
  daisyui: {
    themes: [catppuccin('latte'), 'light'],
  },
}
```

project dependencies like this:
```
dependencies:
@vercel/analytics 1.4.0
chart.js 4.4.6
pinia 2.2.6
vue 3.5.13
vue-router 4.4.5

devDependencies:
@catppuccin/daisyui 1.2.1
@vitejs/plugin-vue 5.2.0
autoprefixer 10.4.20
daisyui 4.12.14
postcss 8.4.49
tailwindcss 3.4.15
vite 5.4.11
```

pnpm version is 9.13.2

node version is 23.1.0

error message

<img width="592" alt="2024-11-16_16-44" src="https://github.com/user-attachments/assets/948326f1-e9a2-432c-80bc-e063b4cfcc99">

**Comment by Liumingxun** [comment]
Since the reproduction hasn't been attached, I forked your [repo](https://github.com/gin-18/lottery) and created this [code sandbox](https://codesandbox.io/p/github/Liumingxun/lottery/main?import=true).

I'm not sure what other changes you made, but I didn't encounter any issues when adding dependencies and configuring them. And maybe you can just `console.log(catppuccin)` to gather more information!

You can refer to my [commit](https://github.com/Liumingxun/lottery/commit/5484d51b8c96301015ad8ce1d6ca79deb27aaf3b), and I can submit a PR for you if needed.

**Comment by gin-18** [comment]
Sorry for not providing more information about the repo. I want to replace vuetify with daisyui in the original repo. 

Now, I configure my repo according to your commit and still get this problem. But when I downgrade the node version from 23.1.0 to 22.11.0, the problem is solved. 

I will close this issue now. 

Thank you very much for your answer :v: .
